### ISSUE TITLE
Default billing and shipping addresses are not saved

### ISSUE THREAD

**Issue by junajan** [sphereio/customer-import#4]
### Steps to reproduce the behavior

When I try to import file with this structure:

```
{
    "customers": [{
        "firstName": "FirstName",
        "lastName": "LastName",
        "custom": {
            "type": {
                "key": "grid-customer"
            },
            "fields": {
                "standardLanguage": "de",
                "standardCurrency": "EUR",
                "anonymusCustomer": true,
                "approvalStatus": true,
                "newsletter": false
            }
        },
        "password": "somePassword",
        "email": "someEmail",
        "customerNumber": "18143",
        "externalId": "someExternalId",
        "addresses": [{
            "firstName": "FirstName",
            "lastName": "LastName",
            "streetName": "Street 12a",
            "postalCode": "40668",
            "city": "CityName",
            "country": "DE"
        }, {
            "firstName": "FirstName",
            "lastName": "LastName",
            "streetName": "Street 12a",
            "postalCode": "40668",
            "city": "CityName",
            "country": "DE"
        }],
        "defaultBillingAddress": 0,
        "defaultShippingAddress": 1
    }]
}
```
### Actual behavior

It imports customer but it does not create defaultBilling and Shipping address flags so if I look in admin.sphere.io, customer have imported two addresses but without flags. If I import customer object directly using impex, it works.
### Expected behavior

After import, customer should have imported two addresses and they should be marked as defaultBilling and defaultShipping address.

**Comment by PhilippSpo** [comment]
Thanks for this nice bug report 👍
At the moment it is not possible to set `defaultBillingAddress` and `defaultShippingAddress` per customer, but for the whole import as mentioned in the [readme](https://github.com/sphereio/customer-import/blob/master/README.md#configuration). You can see an example of how this currently may be used also in the [readme](https://github.com/sphereio/customer-import/blob/master/README.md#direct-usage).

**Comment by junajan** [comment]
@PhilippSpo so theoretically it should be enough to add those two attributes to schema validation here? https://github.com/sphereio/customer-import/blob/master/src/schema.js

**Comment by PhilippSpo** [comment]
Not quite, because they would be [potentially overwritten later](https://github.com/sphereio/customer-import/blob/master/src/customer-import.js#L71).
What should happen if one provides the default addresses for the whole importer and different addresses per customer? Should it prefer the ones made on the customer? Should it throw an error?
